---
- name: Copiar archivos a hosts
  hosts: bdatos_desa
  
  tasks:
    - name: Copia archivos
      copy:
        src: '{{item}}'
        dest: /home/oracle/
        owner: oracle
        group: oinstall
        mode: 0755
      loop:
        - "{{ playbook_dir }}/dblinks.sh"
        - "{{ playbook_dir }}/ora_inst_prod.txt"
       
    