---
- name: Ejecucion script para obtener dblinks a produccion
  hosts: bdatos_desa
  
  tasks: 
    - name: Ejecutar script 
      shell: /home/oracle/dblinks.sh
      notify:
        - Eliminar archivos
  
  handlers: 
    - name: Eliminar archivos
      file:
        path: '{{item}}'
        state: absent
      loop: 
        - /home/oracle/dblinks.sh
        - /home/oracle/ora_inst_prod.txt
